//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_de_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public Documento()
        {
            this.DetalleDocumento = new HashSet<DetalleDocumento>();
        }
    
        public string Codigo { get; set; }
        public string Tipo { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Vendedor { get; set; }
    
        public virtual ICollection<DetalleDocumento> DetalleDocumento { get; set; }
        public virtual Vendedor Vendedor1 { get; set; }
    }
}
