//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_de_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vino
    {
        public Vino()
        {
            this.DetalleDocumento = new HashSet<DetalleDocumento>();
        }
    
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Color { get; set; }
        public int Ano { get; set; }
        public int Precio { get; set; }
        public int Existencia { get; set; }
    
        public virtual ICollection<DetalleDocumento> DetalleDocumento { get; set; }
    }
}
